version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    volumes:
      - .:/code:cached
    ports:
      - 8000:8000
    tty: true
    stdin_open: true
    depends_on:
      - db
    command: python app/django/manage.py runserver 0.0.0.0:8000
